# Это файл конфигурации сборки для GitHub Actions (или локальной сборки).
# ZMK будет собирать отдельные прошивки для каждой указанной конфигурации.
# Здесь определены три сборки: для левой половины, правой и файл сброса.

# Список прошивок для сборки
include:
  # 1. Сборка для ЛЕВОЙ половины (центральной / master)
  - board: nice_nano_v2       # Ваш микроконтроллер
    shield: corne_left        # Конфигурация для левой половины Corne
    keymap: corne             # Имя вашей раскладки (файл .keymap)

  # 2. Сборка для ПРАВОЙ половины (периферийной / slave)
  - board: nice_nano_v2
    shield: corne_right       # Конфигурация для правой половины Corne
    keymap: corne             # Раскладка должна совпадать с левой

# РАСШИРЕННЫЕ ОПЦИИ (можно добавить при необходимости)
 # 3. Сборка файла для полного сброса настроек (Bond Clear и другие)
 - board: nice_nano_v2
   shield: settings_reset    # Специальный "щит" для сброса

 # 4. Сборка для тестирования платы (проверка GPIO, если есть проблемы)
 - board: nice_nano_v2
   shield: tester_pro_micro  # Прошивка-"тестер" для диагностики

 # 5. Если у вас другая версия Corne (например, с переключателями Choc)
 # - board: nice_nano_v2
 #   shield: corne_choc_left
 #   keymap: corne_split

# Глобальные настройки для ВСЕХ сборок (если нужно)
# Эти параметры применяются ко всем конфигурациям выше, если не переопределены явно.
# build_args:
  # Можно передавать аргументы для CMake, например:
  # - ZMK_CONFIG: /absolute/path/to/your/config (обычно не требуется в GitHub Actions)
